name: genzspace
description: The Student-Only Social Network of India

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
# firebase_core: ^2.24.2
# firebase_auth: ^4.15.3
# cloud_firestore: ^4.13.6
# firebase_storage: ^11.5.6
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# dependency_overrides:
#   firebase_core: 2.15.1
#   firebase_auth: 4.7.3
#   cloud_firestore: 4.9.1
#   firebase_storage: 11.2.6
#   firebase_core_web: 2.6.0
#   firebase_auth_web: 4.3.0
#   firebase_storage_web: 3.4.0

flutter:
  uses-material-design: true
  # Remove any fonts section if it exists