// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgw_X77NQkAaq5IQonYmbo5ExnUfXmPEI',
    appId: '1:839050117776:web:ceadd7043e4cc3aafbce15',
    messagingSenderId: '839050117776',
    projectId: 'genzspace',
    authDomain: 'genzspace.firebaseapp.com',
    storageBucket: 'genzspace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgw_X77NQkAaq5IQonYmbo5ExnUfXmPEI',
    appId: '1:839050117776:android:ceadd7043e4cc3aafbce15',
    messagingSenderId: '839050117776',
    projectId: 'genzspace',
    storageBucket: 'genzspace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgw_X77NQkAaq5IQonYmbo5ExnUfXmPEI',
    appId: '1:839050117776:ios:ceadd7043e4cc3aafbce15',
    messagingSenderId: '839050117776',
    projectId: 'genzspace',
    storageBucket: 'genzspace.appspot.com',
    iosBundleId: 'com.anu.GenZSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgw_X77NQkAaq5IQonYmbo5ExnUfXmPEI',
    appId: '1:839050117776:ios:ceadd7043e4cc3aafbce15',
    messagingSenderId: '839050117776',
    projectId: 'genzspace',
    storageBucket: 'genzspace.appspot.com',
    iosBundleId: 'com.anu.GenZSpace',
  );
}
