// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// Firebase is currently disabled for this project
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Firebase is currently disabled
  // This is a placeholder class to prevent compilation errors
  static Map<String, dynamic> get currentPlatform {
    return {
      'apiKey': 'placeholder',
      'appId': 'placeholder',
      'messagingSenderId': 'placeholder',
      'projectId': 'placeholder',
    };
  }
}