name: Deploy Website to Hostinger

on:
  push:
    branches: [ main, master ]
    paths:
      - 'website/**'
      - '.github/workflows/deploy-website.yml'
    paths-ignore:
      - 'lib/**'
      - 'android/**'
      - 'ios/**'
      - 'firebase.json'
      - 'firestore.rules'
      - 'firestore.indexes.json'
      - 'storage.rules'
  workflow_dispatch: # Allow manual trigger

env:
  HOSTINGER_HOST: genzspace.in
  HOSTINGER_USERNAME: ${{ secrets.HOSTINGER_USERNAME }}
  HOSTINGER_PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}
  HOSTINGER_PORT: 21

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd website
        npm install -g html-validator
        npm install -g imagemin-cli
        npm install -g imagemin-pngquant
        npm install -g imagemin-mozjpeg
        
    - name: Validate HTML
      run: |
        cd website
        html-validator --file index.html --verbose
        html-validator --file privacy.html --verbose
        html-validator --file 404.html --verbose
        
    - name: Verify website files
      run: |
        cd website
        echo "✅ Website files verified:"
        ls -la
        echo "✅ Main pages:"
        echo "  - index.html (main page)"
        echo "  - privacy.html (privacy policy)"
        echo "  - 404.html (error page)"
        echo "✅ SEO files:"
        echo "  - robots.txt"
        echo "  - sitemap.xml"
        echo "✅ Performance files:"
        echo "  - .htaccess"
        
    - name: Update sitemap with current date
      run: |
        cd website
        sed -i "s/2024-12-19/$(date +%Y-%m-%d)/g" sitemap.xml
        echo "✅ Sitemap updated with current date"
        
    - name: Final verification
      run: |
        cd website
        echo "🚀 Ready to deploy:"
        echo "✅ Main website: index.html"
        echo "✅ Privacy policy: privacy.html"
        echo "✅ Error page: 404.html"
        echo "✅ SEO files: robots.txt, sitemap.xml"
        echo "✅ Performance: .htaccess"
        echo "✅ All files ready for deployment!"
        
    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ env.HOSTINGER_HOST }}
        username: ${{ env.HOSTINGER_USERNAME }}
        password: ${{ env.HOSTINGER_PASSWORD }}
        port: ${{ env.HOSTINGER_PORT }}
        local-dir: ./website/
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/.env.*
          **/README.md
          **/.DS_Store
          **/Thumbs.db
          **/website/README.md
          **/website/assets/images/README.md
        include: |
          index.html
          privacy.html
          404.html
          robots.txt
          sitemap.xml
          .htaccess
          assets/**
          
    - name: Verify deployment
      run: |
        echo "🚀 Website deployed successfully to Hostinger!"
        echo "🌐 Live URL: https://genzspace.in"
        echo "📱 Privacy Policy: https://genzspace.in/privacy.html"
        
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Website deployment completed successfully!"
        echo "🔗 Live site: https://genzspace.in"
        echo "📄 Privacy Policy: https://genzspace.in/privacy.html"
        echo "🔍 Sitemap: https://genzspace.in/sitemap.xml"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Website deployment failed!"
        echo "Please check the logs for more details."